server:
  port: 7002

#eureka配置
eureka:
  instance:
    hostname: localhost  #Eureka服务端的实例名称,localhost代表服务器的地址，最后要换的
  client:
    register-with-eureka: false  #表示是否向eureka注册中心注册自己
    fetch-registry: false       #fetch-registry如果为false, 则表示自己为注册中心
    service-url:                # 监控页面
     # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
     aultZone: http://localhost:7001/eureka/,http://127.0.0.1:7003/eureka/