server:
  port: 80

#Eureka配置
eureka:
  client:
    register-with-eureka: false  #不向eureka注册自己
    service-url:
      #做集群需要关联集群的eureka服务器的地址,其实端口号都应该是7001，
      #关联的只是服务器地址，这里因为只有一台电脑，就用了端口号代替
      defaultZone: http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
      #常见错误
      #参考文档博客园 https://www.cnblogs.com/cangqinglang/p/11704475.html